# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/mojito/setup-makefiles.sh

# A/B
AB_OTA_PARTITIONS += \
    vendor

# Dynamic
BOARD_QTI_DYNAMIC_PARTITIONS_PARTITION_LIST += vendor

# Vendor
BOARD_PREBUILT_VENDORIMAGE := vendor/xiaomi/mojito/vendor.img
